# Generated by Django 4.2.23 on 2025-10-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.FileField(
                blank=True,
                help_text="Optional image URL",
                null=True,
                upload_to="ads/images",
            ),
        ),
    ]
