# Generated by Django 4.2.4 on 2023-08-12 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("updated_at",)},
        ),
        migrations.RenameField(
            model_name="chatsession",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="chatsession",
            old_name="updated",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="updated",
            new_name="updated_at",
        ),
    ]
