# Generated by Django 4.2.4 on 2023-08-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_sourcedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="ip_address",
            field=models.GenericIPAddressField(default=None, null=True),
        ),
    ]
