# Generated by Django 4.2.4 on 2023-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vector_store_binary',
            field=models.BinaryField(null=True),
        ),
    ]
