# Generated by Django 4.2.4 on 2023-08-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_game_vector_store_binary"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="public_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
