# Generated by Django 4.2.4 on 2023-08-25 18:14

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_alter_game_card_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="card_image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                default="games/card_images/default.png",
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[900, None],
                upload_to="games/card_images",
            ),
        ),
    ]
