# Generated by Django 4.2.4 on 2023-09-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_game_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="faiss_file",
            field=models.FileField(
                blank=True, null=True, upload_to="games/faiss_indexes"
            ),
        ),
        migrations.RunSQL(
            """
            UPDATE games_game SET ingested = false;
            """
        ),
    ]
