# Generated by Django 4.2.4 on 2023-09-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_game_faiss_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ignore_pages",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="setup_pages",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
