# Generated by Django 4.2.23 on 2025-08-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0010_document_ignore_pages_document_setup_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="rulebook_file",
            field=models.FileField(blank=True, null=True, upload_to="games/rulebooks"),
        ),
    ]
