# Generated by Django 4.2.23 on 2025-08-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0011_document_rulebook_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
