name: Test
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11.4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run coverage run --source='.' manage.py test
      - name: List coverage
        run: |
          poetry run coverage report
