name: Test
on: [pull_request, push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis/redis-stack-server:latest
        ports:
          - 6379:6379
    env:
      DEBUG: 'on'
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DATABASE_URL: 'pgsql://postgres:postgres@localhost:5432/postgres'
      REDIS_URL: 'redis://localhost:6379'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.4
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      - name: Run tests
        run: |
          poetry run coverage run --source='.' manage.py test
      - name: List coverage
        run: |
          poetry run coverage report
